music_directory		"/home/marouane/Music"
db_file				"~/.mpd/database"
pid_file			"~/.mpd/pid"
state_file			"$XDG_RUNTIME_DIR/mpd/state"
# For network
bind_to_address		"localhost"
# And for Unix Socket
bind_to_address		"~/.mpd/socket"
port				"6600"

restore_paused "yes"

auto_update	"yes"
follow_outside_symlinks	"yes"
follow_inside_symlinks		"yes"

audio_output {
	type		"alsa"
	name		"My ALSA Device"
}

audio_output {
	type 		"pulse"
	name 		"pipewire-Pulse"
	
}
